#!/usr/bin/env node
/**
 * Brings the real designs into stage 4, so the theme picker shows exactly what ships.
 *
 *   node scripts/sync-themes.mjs      # runs before `dev` and `build` (predev / prebuild)
 *
 * For every theme in src/themes/<id>/ (the real app's, generated from its DESIGN.md by
 * `npm run design:sync`), copies theme.css + fonts.css into app/themes/<id>.css and the theme's
 * font files and art into public/, and writes app/themes/themes.json (id, name, description from
 * the DESIGN.md front matter). All outputs are gitignored: a token edit in any DESIGN.md reaches
 * this stage on its next build, with no copy to keep in step by hand.
 */
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const REPO = path.resolve(HERE, '../..');
const THEMES = path.join(REPO, 'src/themes');
const OUT_CSS = path.join(HERE, 'app/themes');
/** Under a path prefix (stages/next.config.base.ts) the copied CSS must point at prefixed files. */
const BASE = process.env.NEXT_PUBLIC_BASE_PATH ?? '';
const prefixed = (css) => (BASE ? css.replace(/url\((["']?)\/(fonts|assets)\//g, `url($1${BASE}/$2/`) : css);
/** The approved design leads the picker; the rest follow alphabetically. */
const DEFAULT = 'botanical-deco';

function frontMatter(md) {
  const fm = md.match(/^---\n([\s\S]*?)\n---/)?.[1] ?? '';
  const name = fm.match(/^name:\s*(.+)$/m)?.[1]?.trim() ?? '';
  const folded = fm.match(/^description:\s*>-?\n((?:[ \t]+.+\n?)+)/m)?.[1];
  const description = folded ? folded.split('\n').map((l) => l.trim()).filter(Boolean).join(' ') : (fm.match(/^description:\s*(.+)$/m)?.[1]?.trim() ?? '');
  return { name, description };
}

rmSync(OUT_CSS, { recursive: true, force: true });
mkdirSync(OUT_CSS, { recursive: true });

const ids = readdirSync(THEMES, { withFileTypes: true })
  .filter((d) => d.isDirectory() && existsSync(path.join(THEMES, d.name, 'theme.css')))
  .map((d) => d.name)
  .sort((a, b) => (a === DEFAULT ? -1 : b === DEFAULT ? 1 : a.localeCompare(b)));

const meta = [];
for (const id of ids) {
  const dir = path.join(THEMES, id);
  const css = ['fonts.css', 'theme.css'].filter((f) => existsSync(path.join(dir, f))).map((f) => readFileSync(path.join(dir, f), 'utf8'));
  writeFileSync(path.join(OUT_CSS, `${id}.css`), `/* Copied from src/themes/${id}/ by scripts/sync-themes.mjs. Do not edit. */\n${prefixed(css.join('\n'))}`);
  for (const sub of ['fonts', 'assets/art']) {
    const from = path.join(REPO, 'public', sub, id);
    const to = path.join(HERE, 'public', sub, id);
    rmSync(to, { recursive: true, force: true });
    if (existsSync(from)) cpSync(from, to, { recursive: true });
  }
  meta.push({ id, ...frontMatter(readFileSync(path.join(dir, 'DESIGN.md'), 'utf8')), approved: id === DEFAULT });
}
writeFileSync(path.join(OUT_CSS, 'themes.json'), `${JSON.stringify(meta, null, 2)}\n`);
writeFileSync(
  path.join(OUT_CSS, 'index.css'),
  `/* Generated by scripts/sync-themes.mjs. */\n${ids.map((id) => `@import "./${id}.css";`).join('\n')}\n`,
);
console.log(`sync-themes: ${ids.join(', ')}`);
