// GENERATED by scripts/generate-atlas.mjs. Do not edit by hand.
// Equal Earth, 1000 × 437 drawing units, latitudes -58° to 84°. The drawing is public/assets/atlas/world.svg.
export const ATLAS_FRAME = {"width":1000,"height":437,"scale":184.731568,"top":241.391167,"north":84,"south":-58} as const;

/** The drawing's layers, each a <path id> in world.svg. */
export const ATLAS_LAYERS = ["land","lakes","borders","states","graticule","equator","tropics","outline"] as const;
