// GENERATED by scripts/generate-atlas-region.mjs. Do not edit by hand.
// The close-up drawn inside this rectangle of the world drawing (public/assets/atlas/midwest.svg):
// longitudes -93° to -83°, latitudes 40° to 47.5°.
export const REGION_FRAME = {"x":282.672,"y":74.872,"w":12.975,"h":23.412} as const;

/** The close-up's layers, each a <path id> in midwest.svg. */
export const REGION_LAYERS = ["land","urban","lakes","shore","city","rivers","roads","states"] as const;
