// GENERATED by scripts/generate-atlas-region.mjs. Do not edit by hand.
// The close-up drawn inside this rectangle of the world drawing (public/assets/atlas/midwest.svg):
// longitudes -95° to -82°, latitudes 39° to 47.5°.
export const REGION_FRAME = {"x":277.998,"y":74.872,"w":18.862,"h":26.66} as const;
/** midwest.svg's content hash: the page asks for `midwest.svg?v=${REGION_VERSION}`, so a cached copy never outlives its frame. */
export const REGION_VERSION = 'dc49c1efeaef';

/** The close-up's layers, each a <path id> in midwest.svg. */
export const REGION_LAYERS = ["land","urban","lakes","shore","city","rivers","roads","states"] as const;
