/**
 * Generates `docs/ops/activation-matrix.md` from the code, and fails the build when the committed
 * file no longer matches (`--check`).
 *
 * Written by hand, this table is the single most likely document in the repository to become a
 * lie: nine flags, seventeen provider seams and about forty environment variables, every one of
 * which moves when a level lands. This whole run kept finding pages that described a version of
 * the site that no longer existed — a hand-maintained activation matrix is that defect with a
 * deploy attached, because the reader is an operator deciding what to switch on in production.
 *
 * So the modes are the ones `describeProviders()` actually resolves with the current environment,
 * the flag defaults are read from the registry, and the variables listed against each provider are
 * the ones its own source reads. Prose that a generator cannot derive lives above the marker and
 * is never touched.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { argv, cwd, exit } from 'node:process';
import { join } from 'node:path';
import { FEATURE_FLAGS, READINESS_GATED, type FeatureFlag } from '@/contracts/flags';
import { describeProviders } from '@/providers';

const ROOT = cwd();
const DOC = join(ROOT, 'docs/ops/activation-matrix.md');
const BEGIN = '<!-- BEGIN GENERATED: npm run docs:activation -->';
const END = '<!-- END GENERATED -->';

/** Which environment variables a provider kind's own source reads. Derived, never listed by hand. */
function varsFor(kind: string): string[] {
  let out = '';
  try {
    out = execFileSync('git', ['grep', '-oh', '-E', 'env\\.[A-Z][A-Z0-9_]*', '--', `src/providers/${kind}/`], {
      cwd: ROOT,
      encoding: 'utf8',
    });
  } catch {
    return [];
  }
  const names = new Set(out.split('\n').filter(Boolean).map((s) => s.replace(/^env\./, '')));
  names.delete('NODE_ENV');
  return [...names].sort();
}

/** One flag's row: the default, whether a readiness switch is also required, and how to override. */
function flagRows(): string[] {
  return (Object.keys(FEATURE_FLAGS) as FeatureFlag[]).sort().map((name) => {
    const on = FEATURE_FLAGS[name];
    const gated = READINESS_GATED.includes(name);
    const how = gated
      ? `\`FLAG_${name}=on\` **and** the readiness switch on \`/admin/flags\``
      : `\`FLAG_${name}=${on ? 'off' : 'on'}\``;
    return `| \`${name}\` | ${on ? 'on' : '**off**'} | ${gated ? 'yes — legal gate' : 'no'} | ${how} |`;
  });
}

function providerRows(): string[] {
  return describeProviders()
    .sort((a, b) => a.kind.localeCompare(b.kind))
    .map((p) => {
      const vars = varsFor(p.kind);
      const caps = Object.entries(p.capabilities)
        .filter(([, v]) => v)
        .map(([k]) => k);
      const warn = p.config.warnings.length > 0 ? p.config.warnings.join('; ') : '';
      return `| \`${p.kind}\` | ${p.name} | ${p.mode} | ${vars.length > 0 ? vars.map((v) => `\`${v}\``).join('<br>') : '—'} | ${caps.length > 0 ? caps.join(', ') : '—'} | ${warn} |`;
    });
}

/**
 * This generator describes the registry with NO database, because that is the state it can measure
 * from a script. One kind refuses to build without one, so its row reads `unavailable` here and
 * never does in the running app — both real callers (`src/app/api/health/route.ts` and
 * `src/capabilities/ops/admin_provider_status.ts`) pass the live connection. Named rather than
 * quietly special-cased, and derived from the failure itself so a second such kind cannot slip in.
 */
const needsDb = describeProviders()
  .filter((p) => p.config.warnings.some((w) => /requires a database/i.test(w)))
  .map((p) => p.kind);

const generated = [
  BEGIN,
  '',
  `Generated by \`npm run docs:activation\` from \`src/contracts/flags.ts\` and \`src/providers/\`.`,
  'Do not edit between the markers; edit the code and regenerate.',
  '',
  '## Feature flags',
  '',
  '| Flag | Default | Readiness switch also required | To change it |',
  '|---|---|---|---|',
  ...flagRows(),
  '',
  'A readiness-gated flag does nothing on the environment variable alone. Both gates exist because',
  'each protects a different decision: the variable is an operator turning a capability on, the',
  'readiness switch is a person recording that the legal precondition has been met.',
  '',
  '## Provider seams',
  '',
  'Modes below are the ones this repository resolves **with no environment configured** — which is',
  'the state a fresh clone, the test suite and CI all run in. Every kind falls back to a mock rather',
  'than failing, and `FORCE_MOCK_PROVIDERS=1` pins every one of them there regardless of keys.',
  '',
  '| Kind | Implementation | Mode | Variables its source reads | Operations available | Notes |',
  '|---|---|---|---|---|---|',
  ...providerRows(),
  '',
  needsDb.length > 0
    ? `This generator describes the registry from a script, with no database connection. ${needsDb
        .map((k) => `\`${k}\``)
        .join(', ')} refuses to build without one, so ${needsDb.length === 1 ? 'its row reads' : 'their rows read'} \`unavailable\` above and never ${
        needsDb.length === 1 ? 'does' : 'do'
      } in the running app — \`src/app/api/health/route.ts\` and \`src/capabilities/ops/admin_provider_status.ts\` both pass the live connection.`
    : 'Every kind resolves without a database connection.',
  '',
  END,
].join('\n');

const check = argv.includes('--check');
let current = '';
try {
  current = readFileSync(DOC, 'utf8');
} catch {
  if (check) {
    console.error('docs/ops/activation-matrix.md does not exist. Run `npm run docs:activation`.');
    exit(1);
  }
}

const start = current.indexOf(BEGIN);
const stop = current.indexOf(END);
const prose = start >= 0 ? current.slice(0, start) : '';
const tail = stop >= 0 ? current.slice(stop + END.length) : '\n';
const next = `${prose}${generated}${tail}`;

if (check) {
  if (next === current) {
    console.log('docs/ops/activation-matrix.md is up to date.');
    exit(0);
  }
  console.error('docs/ops/activation-matrix.md is out of date with the code. Run `npm run docs:activation`.');
  exit(1);
}
writeFileSync(DOC, next);
console.log(`Wrote ${DOC}`);
